---
apiVersion: v1                                                            
kind: Pod                                                                 
metadata:                                                                 
  name: app                                                               
  labels:                                                                 
    app: demo                                                             
    run: demo                                                             
spec:                                                                     
  containers:                                                             
    - name: app                                                             
      image: ghcr.io/den-vasyliev/go-demo-app                               
      ports:
        - containerPort: 8000
          name: http
